# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'third-party/grantlee' : '@stable'
    'frameworks/kdesignerplugin' : '@latest'
    'frameworks/kcontacts' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-contacts' : '@latest'
    'kde/pim/kimap' : '@latest'
    'kde/pim/kmime' : '@latest'
    'kde/pim/kpimtextedit' : '@latest'
    'kde/pim/libkdepim' : '@latest'
